[workspace]
members = [
    "crates/01-hello",
    "crates/02-primitives",
    "crates/03-custom-types",
    "crates/04-variable-bindings",
    "crates/05-casting",
    "crates/06-expressions",
    "crates/07-flow-of-control",
    "crates/08-functions",
    "crates/09-modules",
    "crates/10-crates",
    "crates/11-cargo",
    "crates/12-attributes",
    "crates/13-generics",
    "crates/14-scoping-rules",
    "crates/15-traits",
    "crates/16-macros",
    "crates/17-error-handling",
    "crates/18-std-library-types",
    "crates/19-std-misc",
    "crates/20-testing",
    "crates/21-unsafe",
    "crates/cli-minigrep",
    "crates/cli-todo",
    "crates/cli-logparse",
]
